name: Branch Name Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Determine branch name
        id: get_branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Check branch name
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch_name }}"
          AUTHOR_NAME=${{ github.actor }}

          if [[ ! "$BRANCH_NAME" =~ ^$AUTHOR_NAME ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not start with username '$AUTHOR_NAME'."
            exit 1
          fi

          echo "Branch name '$BRANCH_NAME' is valid."
